### ISSUE TITLE
Couples

### ISSUE THREAD

**Issue by asap1en** [Damianonymous/ChaturbateRecorder#1]
I have noticed that there are certain models it will rarely record (if ever), after a bit of snooping it seems like all of the models I have noticed this issue with are tagged as couples.  I can tell the code handles couples in a separate loop at one point and I fear it may have an error in it (overwriting the array maybe?)

**Comment by genebeck** [comment]
Same issue with my install.  Right now all the couple cams and most female cams do not ever record.  I have about a dozen or so model, and have tested with models that are really online.  I think this may be a result of how Chaturbate processes requests.

**Comment by Damianonymous** [comment]
On my Windows system, the program has not been working properly for a long time. This is only the archive of the repository removed by DMCA, the only contact with the author I know is his Reddit account: https://www.reddit.com/user/Beaston02 You can try a similar application in Python using youtube-dl: https://github.com/oliverjrose99/Recordurbate Personally, I recommend a regularly updated and easy-to-use application for many webcam sites: https://github.com/0xboobface/ctbrec
